appname = ecommerce_gateway
httpport = 8070
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
authenticationBaseUrl = http://localhost:5080
customerBaseUrl = http://localhost:5083
itemBaseUrl = http://localhost:5082
systemBaseUrl = http://localhost:5088
transactionsBaseUrl = http://localhost:5085
auditTrailBaseUrl = http://localhost:5091
notificationsBaseUrl = http://localhost:5090
paymentBaseUrl = http://localhost:5088
# imagesBaseUrl = "/Users/bedeabbe/Desktop/projects/golang/images"
imagesBaseUrl = "https://images.ecommerce.readils.com"
branchManagerRoleName = "Branch Manager"
managingDirectorRoleName = "Managing Director"
superAdminRoleName = "SUPER_ADMIN"

